#!/bin/sh

test_file=${1:-tests.rb}

echo "Running tests in $test_file..."
SDL_VIDEODRIVER=dummy SDL_AUDIODRIVER=dummy ./dragonruby mygame --test $test_file | tee logs/tests.log

# This grep call is a workaround since DragonRuby does not return an error
# exit code when the tests fail
grep '\[Game\] 0 test(s) failed.' logs/tests.log
